Repository felangel/hydrated_bloc, pull requests merged in 2019-07, with the labels that each got.

#6 More detailed usage description.
  README.md
Labels: documentation

#7 Update HydratedBlocStorage to use getTemporaryDirectory instead of getApplicationDocumentsDirectory
  CHANGELOG.md
  example/ios/Podfile.lock
  example/ios/Runner.xcodeproj/project.pbxproj
  example/pubspec.lock
  lib/src/hydrated_bloc_storage.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#11 hydrated_bloc v0.3.1
  CHANGELOG.md
  example/pubspec.lock
  lib/src/hydrated_bloc_storage.dart
  pubspec.yaml
  test/hydrated_bloc_storage_test.dart
Labels: bug
